# Generated by Django 2.2.6 on 2021-03-30 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, help_text='Расскажите о себе', verbose_name='Об авторе'),
        ),
    ]
