# Generated by Django 2.2.6 on 2021-04-01 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20210330_2238'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
